import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Footer, FooterBanner, HeroBanner, Product } from "../container";
import { client } from "../lib/client";

export default function Home({ products, bannerData }) {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Headset Shopme</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/assets/headphones_a_1.webp" />
        </Head>
        <HeroBanner heroBanner={bannerData.length && bannerData[0]} />
        {console.log(bannerData)}
        <div className="products-heading">
          <h1>headset Products</h1>
        </div>
        <div className="products-container">
          {products?.map((product) => (
            <Product key={product._id} product={product} />
          ))}
        </div>
        <FooterBanner footerBanner={bannerData && bannerData[0]} />
      </div>
    </>
  );
}
export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);

  const bannerQuery = '*[_type == "banner"]';
  const bannerData = await client.fetch(bannerQuery);

  return {
    props: { products, bannerData },
  };
};
